### ISSUE TITLE
Bundle Julia scripts (DiffEqPy.jl) in diffeqpy Python package?

### ISSUE THREAD

**Issue by tkf** [JuliaDiffEq/diffeqpy#22]
Since current DiffEqPy.jl is very small, why not bundle it in the Python package?  I've done it in #19 and it's not difficult.

This way, change in Julia code directly trigger the tests here.  Also, we don't need to worry about DiffEqPy.jl-vs-diffeqpy API compatibility this way (although currently there is no complex API).

**Comment by ChrisRackauckas** [comment]
To be a registered Julia package it needs to have the `.jl` on the end. But won't that clone weird for Python users?

**Comment by tkf** [comment]
What I mean is to get rid of DiffEqPy.jl Julia package entirely and add Julia scripts to diffeqpy Python package.  So not registering any additional package.  It means to bundle some Julia files in diffeqpy and `include` those files, instead of `using DiffEqPy`.

**Comment by ChrisRackauckas** [comment]
could you mock it? I think I see what you're getting at but the exact details where what got me. If it's not a package, are you just `include`ing some path? How do you get that path in Python? Etc.
