### ISSUE TITLE
Crash at "from diffeqpy import de".

### ISSUE THREAD

**Issue by phn** [JuliaDiffEq/diffeqpy#27]
Hello,

Background:

1)

I am using Julia v 0.6.2 and Python 3.6.3 (installed using Continuum's Anaconda) on Ubuntu 16.04 LTS.

2)
I can successfully run DifferentialEquations from within Julia; for example http://docs.juliadiffeq.org/latest/tutorials/dde_example.html. 

3)

I need to run julia with the following command: 

    LD_PRELOAD=/home/phn/bin/anaconda3/envs/py36/lib/libz.so ~/bin/julia-d386e40c17/bin/julia

This command is needed to use pyplot; see https://github.com/JuliaPy/PyPlot.jl/issues/151 .

4)

When installing DifferentialEquations, with ``Pkg.add("DifferentialEquations")``, I had started Julia using the above command and while the particular conda environment I want was activated(i.e., python points to python in this conda environment). I also had to create a symlink "gcc" that points to gcc inside this environment so that I can get Rmath to install. The system gcc I have is old and couldn't compile Rmath.

Issue:

When I run the Python statement "from diffeqpy import de" inside an IPython session, IPython crashes with 
the following error:

In [1]: from diffeqpy import de
PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, C_NULL)) PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, C_NULL)) PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, C_NULL)) PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, C_NULL)) fatal: error thrown and no exception handler available.
PyCall.PyError(msg="ccall(@pysym(PyString_AsStringAndSize), Cint, (PyPtr, Ptr{Ptr{UInt8}}, Ptr{Int}), po, _ps_ptr, _ps_len)", T=PyCall.PyObject(o=0x0000555f8e49ff40), val=PyCall.PyObject(o=0x00007f4a131ea6d0), traceback=PyCall.PyObject(o=0x0000000000000000))
rec_backtrace at /buildworker/worker/package_linux64/build/src/stackwalk.c:84
record_backtrace at /buildworker/worker/package_linux64/build/src/task.c:245
jl_throw at /buildworker/worker/package_linux64/build/src/task.c:564
pyerr_check at /home/phn/.julia/v0.6/PyCall/src/exception.jl:58 [inlined]
pyerr_check at /home/phn/.julia/v0.6/PyCall/src/exception.jl:62 [inlined]
macro expansion at /home/phn/.julia/v0.6/PyCall/src/exception.jl:82 [inlined]
convert at /home/phn/.julia/v0.6/PyCall/src/conversions.jl:111
pystring at /home/phn/.julia/v0.6/PyCall/src/PyCall.jl:224
show at /home/phn/.julia/v0.6/PyCall/src/PyCall.jl:229
show_delim_array at ./show.jl:381
show at ./show.jl:397
unknown function (ip: 0x7f49f839a186)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
show_default at ./show.jl:140
unknown function (ip: 0x7f49f8399c46)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1424 [inlined]
jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:51
print at ./strings/io.jl:29
unknown function (ip: 0x7f49f83993c6)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
#print_to_string#229 at ./strings/io.jl:102
pyraise at /home/phn/.julia/v0.6/PyCall/src/exception.jl:127
unknown function (ip: 0x7f49f8398f72)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
_pyjlwrap_call at /home/phn/.julia/v0.6/PyCall/src/callback.jl:56
unknown function (ip: 0x7f49f838d735)
jl_call_fptr_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:339 [inlined]
jl_call_method_internal at /buildworker/worker/package_linux64/build/src/julia_internal.h:358 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:1926
pyjlwrap_call at /home/phn/.julia/v0.6/PyCall/src/callback.jl:63
unknown function (ip: 0x7f49f8363a9f)
_PyObject_FastCallDict at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e11f00d)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e118b8a)
unknown function (ip: 0x555f8e11ef94)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e118b8a)
unknown function (ip: 0x555f8e11ef94)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
PyEval_EvalCodeEx at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
PyEval_EvalCode at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e13df2d)
PyCFunction_Call at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e117f23)
unknown function (ip: 0x555f8e118dc0)
unknown function (ip: 0x555f8e11ef94)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e118b8a)
unknown function (ip: 0x555f8e11ef94)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e118b8a)
unknown function (ip: 0x555f8e11ef94)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e118b8a)
unknown function (ip: 0x555f8e11ef94)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
_PyFunction_FastCallDict at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
_PyObject_FastCallDict at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
_PyObject_CallMethodIdObjArgs at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
PyImport_ImportModuleLevelObject at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e12a1d9)
PyCFunction_Call at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e117f23)
unknown function (ip: 0x555f8e118dc0)
unknown function (ip: 0x555f8e11ef94)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
_PyFunction_FastCallDict at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
_PyObject_FastCallDict at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
_PyObject_CallMethodIdObjArgs at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
PyImport_ImportModuleLevelObject at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
PyEval_EvalCodeEx at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
PyEval_EvalCode at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e13df2d)
_PyCFunction_FastCallDict at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e11eebb)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e117f23)
unknown function (ip: 0x555f8e118dc0)
unknown function (ip: 0x555f8e11ef94)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e117f23)
unknown function (ip: 0x555f8e118dc0)
unknown function (ip: 0x555f8e11ef94)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e11828d)
unknown function (ip: 0x555f8e118dc0)
unknown function (ip: 0x555f8e11ef94)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e117f23)
unknown function (ip: 0x555f8e118dc0)
unknown function (ip: 0x555f8e11ef94)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e117f23)
unknown function (ip: 0x555f8e118dc0)
unknown function (ip: 0x555f8e11ef94)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e118b8a)
unknown function (ip: 0x555f8e11ef94)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e117f23)
_PyFunction_FastCallDict at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
_PyObject_FastCallDict at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
_PyObject_Call_Prepend at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
PyObject_Call at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e117f23)
unknown function (ip: 0x555f8e118dc0)
unknown function (ip: 0x555f8e11ef94)
_PyEval_EvalFrameDefault at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
PyEval_EvalCodeEx at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
PyEval_EvalCode at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
unknown function (ip: 0x555f8e194ce3)
PyRun_FileExFlags at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
PyRun_SimpleFileExFlags at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
Py_Main at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
main at /home/phn/bin/anaconda3/envs/py36/bin/python (unknown line)
__libc_start_main at /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:291
unknown function (ip: 0x555f8e1470d9)

----

Hope this helps you identify the problem(either on my side or with diffeqpy). Let me know if you need more information.

Thanks.

Regards,
Prasanth

**Comment by ChrisRackauckas** [comment]
This may be an installation problem with pyjulia. Try this code:

```julia
import julia
j = julia.Julia()
j.sind(90)
```

**Comment by phn** [comment]
Hello Chris,

At the line 

```python
j = julia.Julia()
```

I get

In [3]: j = julia.Julia()
PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, C_NULL)) PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, C_NULL)) PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, C_NULL)) PyError (ccall(@pysym(:PyObject_Call), PyPtr, (PyPtr, PyPtr, PyPtr), o, arg, C_NULL)) 

I went ahead and ran the line 

```python
j.sind(90)
```
and the system crashed with what looks like the same message as in by first comment.

Regards,
Prasanth

**Comment by ChrisRackauckas** [comment]
This is a pyjulia issue then. Open up an issue over at https://github.com/JuliaPy/pyjulia

**Comment by phn** [comment]
Hello Chris,

Thanks for your time. I have opened an issue at https://github.com/JuliaPy/pyjulia/issues/164.

Regards,
Prasanth
