### ISSUE TITLE
[Documentation] How to use GeometricIntegrators.jl in diffeqpy?

### ISSUE THREAD

**Issue by homocomputeris** [JuliaDiffEq/diffeqpy#31]
How can I use GeometricIntegrators.jl in Python? I haven't found anything in diffeqpy docs about importing this submodule

**Comment by ChrisRackauckas** [comment]
You need to install GeometricIntegratorsDiffEq.jl in Julia, and then those algorithms will be accessible through the solve commands when you import GeometricIntegratorsDiffEq

**Comment by homocomputeris** [comment]
Thanks for the reply.
Could you explain further, how do I import it? Should I import it in python code or in python's interface to julia?
After `Pkg.clone("https://github.com/JuliaDiffEq/GeometricIntegratorsDiffEq.jl")`
in Julia 0.6.4, I've tried and none have worked:

```python
from diffeqpy import GeometricIntegratorsDiffEq
ImportError                               
Traceback (most recent call last)
<ipython-input-48-dac0e3ad23ae> in <module>()
1 from diffeqpy import GeometricIntegratorsDiffEq
ImportError: cannot import name 'GeometricIntegratorsDiffEq' from 'diffeqpy' (/usr/lib/python3.7/site-packages/diffeqpy/__init__.py)
```

```python
import GeometricIntegratorsDiffEq
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-49-a3044d4a5c4c> in <module>()
----> 1 import GeometricIntegratorsDiffEq

ModuleNotFoundError: No module named 'GeometricIntegratorsDiffEq'
```
```

from diffeqpy import Julia
Julia('using GeometricIntegratorsDiffEq')
```

**Comment by homocomputeris** [comment]
It is definitely worthy documenting, but now GeometricIntegrators.jl support versions above 0.7, and diffeqpy doesn't.

**Comment by ChrisRackauckas** [comment]
I would just do `de.eval("using GeometricIntegratorsDiffEq")` and then the methods should be available. Things like SecondOrderODEProblem should just work.

(I will mention that most of the symplectic integrators are actually in OrdinaryDiffEq.jl, as defined here: http://docs.juliadiffeq.org/latest/solvers/dynamical_solve.html#Specialized-OrdinaryDiffEq.jl-Integrators-1 .)

**Comment by homocomputeris** [comment]
Thanks for the help!

I though GI included advanced splitting methods, but it doesn't.

**Comment by ChrisRackauckas** [comment]
I think this can be closed. The main point is just evaling the using and making sure it's already installed. This'll work with any alternative solver package.
