### ISSUE TITLE
Transpile sympy expressions to Julia?

### ISSUE THREAD

**Issue by tkf** [JuliaDiffEq/diffeqpy#32]
Using Python function to define the problem is sadly inefficient.  I think using sympy would be a nice solution for low-dimensional especially if you combine it with StaticArrays.  (Though exposing ModelingToolkit.jl to Python would be much better.)

Here is a quick hack to do it for ODEProblem:

```python
import sympy.printing


def as_ode_f_code(expr, u_syms, p_syms, name=""):
    ubase = sympy.IndexedBase("u")
    pbase = sympy.IndexedBase("p")
    u = [ubase[i + 1] for i in range(len(u_syms))]
    p = [pbase[i + 1] for i in range(len(p_syms))]
    expr = [e.subs(zip(u_syms, u)) for e in expr]
    expr = [e.subs(zip(p_syms, p)) for e in expr]

    du = sympy.Array(expr)
    body = sympy.printing.julia_code(du, contract=False)
    return f"""
    function {name}(u, p, t)
        StaticArrays.@SVector {body}
    end
    """


def jl_lambdify(expr, u_syms, p_syms, t_sym=sympy.symbols('t')):
    from julia import Main
    # eval(Module(), ...) can't be used:
    # https://github.com/JuliaLang/julia/issues/28917
    func = as_ode_f_code(expr, u_syms, p_syms)
    code = f"""
    import StaticArrays
    {func}
    """
    return Main.eval(code)


if __name__ == "__main__":
    def f(u, p, t):
        x, y, z = u
        sigma, rho, beta = p
        return [sigma * (y - x), x * (rho - z) - y, x * y - beta * z]

    u_syms = sympy.symbols("x, y, z")
    p_syms = sympy.symbols("sigma, rho, beta")
    expr = f(u_syms, p_syms, None)
    print(as_ode_f_code(expr, u_syms, p_syms))

    f = jl_lambdify(expr, u_syms, p_syms)
```
It generates (and print):

```julia
function (u, p, t)
    StaticArrays.@SVector [(-u[1] + u[2])*p[1], (p[2] - u[3])*u[1] - u[2], -p[3]*u[3] + u[1]*u[2]]
end
```

The only pitfall I had was that `contract=False` had to be passed to `sympy.printing.julia_code`.

**Comment by ChrisRackauckas** [comment]
I'd accept something, but IMO if I'm going to put work into this it might as well build on ModelingToolkit.jl so that way it gets free support for all of the other stuff down the road.

**Comment by tkf** [comment]
I don't think I'd be using diffeqpy myself since I prefer writing Julia for what it is great at :)  So I'm not planning to open any PRs for this.  I just posted the issue since it was a fun quick hack and it could be useful if some Python users want to implement it.

**Comment by ChrisRackauckas** [comment]
Oh yeah, for sure thanks for posting this. Someone will probably find it useful
