### ISSUE TITLE
How to specifiy algorithm

### ISSUE THREAD

**Issue by Isaac-Severinsen** [JuliaDiffEq/diffeqpy#34]
I'm trying to solve a relatively simple set of ode's that describe the temperature, pressure and composition of a reacting gas mixture down a tube. 

I'm trying to replace scipy solvers with Julia. I am encouraged by the range of algorithms but am deterred by the lack of documentation.

The specific issue is that the composition of species within the mixture become negative, typically changing method will resolve this issue but I can not find how to do it with this package!

I've tried:
sol = de.solve(prob,alg='Rosenbrock23()')
and,
sol = de.solve(prob,alg='Rosenbrock23')

which gives:
RuntimeError: Julia exception: MethodError(DiffEqBase.isadaptive, ("Rosenbrock23()",), 0x000000000000623c)

I tried:
sol = de.solve(prob,'Rosenbrock23')
which gives:

RuntimeError: Julia exception: ErrorException("Inappropiate solve command. The arguments do not make sense. Likely, you gave an algorithm which does not actually exist (or does not <:DiffEqBase.DEAlgorithm)")

Can someone point me in the right direction?
I understand I'm a new user but the error messages given are not particularly helpful.

**Comment by tkf** [comment]
```python
from diffeqpy import de

def f(u,p,t):
    return -u

u0 = 0.5
tspan = (0., 1.)
prob = de.ODEProblem(f, u0, tspan)
sol = de.solve(prob, de.Tsit5())
```

works for me.  Note that autodiff does not work #21 so `de.solve(prob, de.Rosenbrock23())` will fail.

**Comment by ChrisRackauckas** [comment]
The problem is that you needed to preface with `de.`. All things are referenced from the package when doing `import ...`.

>Note that autodiff does not work #21 so de.solve(prob, de.Rosenbrock23()) will fail.

Yup, but `de.solve(prob,de.Rosenbrock23(autodiff=false))` is a fine workaround.
