### ISSUE TITLE
MethodError: no method matching unwrap_cache(::DelayDiffEq.DDEIntegrator...

### ISSUE THREAD

**Issue by tkf** [JuliaDiffEq/diffeqpy#49]
@ChrisRackauckas  This seems to be an API usage error or something:

https://ci.appveyor.com/project/ChrisRackauckas/diffeqpy/builds/24966633/job/534340b3jalo748h#L219

`Julia exception: MethodError: no method matching unwrap_cache(::DelayDiffEq.DDEIntegrator{OrdinaryDiffEq.CompositeAlgorithm{Tuple{OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.Rosenbrock23{0,false,DiffEqBase.DefaultLinSolve,DataType}},OrdinaryDiffEq.AutoSwitch{OrdinaryDiffEq.Tsit5,OrdinaryDiffEq.Rosenbrock23{0,false,DiffEqBase.DefaultLinSolve,DataType},Rational{Int64},Float64}}` (...and so on...)

then

```
Closest candidates are:
  unwrap_cache(!Matched::OrdinaryDiffEq.ODEIntegrator, ::Any) at C:\Users\appveyor\.julia\packages\OrdinaryDiffEq\Cc6K8\src\cache_utils.jl:6
  unwrap_cache(!Matched::StochasticDiffEq.SDEIntegrator, ::Any) at C:\Users\appveyor\.julia\packages\StochasticDiffEq\YRc41\src\cache_utils.jl:2
```

**Comment by ChrisRackauckas** [comment]
@kanav99

**Comment by kanav99** [comment]
Can you give me a MWE which makes it fail? @tkf

**Comment by tkf** [comment]
The test failure occurs while running this:

https://github.com/JuliaDiffEq/diffeqpy/blob/feee104e962ae21641cccf309c73fc0ffaf603b5/diffeqpy/tests/test_dde.py#L6-L23

Translating this back to Julia,

```julia
using DifferentialEquations

function f(du, u, h, p, t)
    du[1] = 1.1/(1 + sqrt(10)*(h(p, t-20)[1])^(5/4)) - 10*u[1]/(1 + 40*u[2])
    du[2] = 100*u[1]/(1 + 40*u[2]) - 2.43*u[2]
end

u0 = [1.05767027/3, 1.030713491/3]

function h(p,t)
  [1.05767027/3, 1.030713491/3]
end

tspan = (0.0, 100.0)
constant_lags = [20.0]
prob = DDEProblem(f,u0,h,tspan,constant_lags=constant_lags)
sol = solve(prob,saveat=0.1)
```

seems to fail with the same error.
